# Task 1

In [8]:
# Write a function to compute 5/0 and use try/except to catch the exceptions.
try:
    
    res=5/0
    print(res)

except ZeroDivisionError:
    print('The denominator can not be zero')

The denominator can not be zero


In [9]:
subjects=['Americans', 'Indians']
verbs=['play','watch']
objects=['Baseball','Cricket']

for i in subjects:
    for j in verbs:
        for k in objects:
            print('{} {} {}'.format(i,j,k))

Americans play Baseball
Americans play Cricket
Americans watch Baseball
Americans watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


# Task 2

In [28]:
# AlexandreTheophile Vandermonde
import numpy as np
def vandermonde(ip, n, inc=False):
    if inc:
        arr=[[x**i for i in range(n)] for x in ip]
    if not inc:
        arr=[[x**i for i in range(n-1,-1,-1)] for x in ip]
    print(np.array(arr))

vandermonde([1,2,3,4,5],3,True)
print('')
vandermonde([1,2,4,6,7],4,False)

[[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]
 [ 1  5 25]]

[[  1   1   1   1]
 [  8   4   2   1]
 [ 64  16   4   1]
 [216  36   6   1]
 [343  49   7   1]]
